### ISSUE TITLE
MetaMask: "signing can have dangerous side effects"

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/smart_contract#8]
https://github.com/forkdelta/forkdelta.github.io/issues/20

MetaMask is currently displaying the following when the user attempts to sign an off-chain order:

Signing this message can have dangerous side effects. Only sign messages from sites you fully trust with your entire account. This dangerous method will be removed in a future version. Read more here.

**Comment by JonathonDunford** [comment]
@betterdelta

**Comment by mmhh1910** [comment]
??

**Comment by JonathonDunford** [comment]
@betterdelta Wanted to tag you here to get your thoughts.

**Comment by mmhh1910** [comment]
Between a rock and a hard place...

I think we should not change this currently. The "signing can have dangerous side effects" is slightly better than the garbage string users would see when switching to personal_sign.

For the details see: https://github.com/0xProject/0x-monorepo/issues/162

This actually looks worse than the current MetaMask warning.

**Comment by JonathonDunford** [comment]
@freeatnet 

I am going to agree with @betterdelta here and close this issue.

Maybe when their proposed fix gets adopted, we can change over, but who knows how long that will be.
